apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  inputs:
    params:
      - name: API_ENDPOINT
        description: The CF API endpoint.
      - name: CF_USER
        description: The CF user.
      - name: CF_PASS
        description: CF user's pass.
      - name: CF_ORG
        description: CF org.
      - name: CF_SPACE
        description: CF space.
      - name: APP_IMAGE
        description: The app image to be deployed.
  steps:
    - name: deploy-app
      image: bikramnehra/base-ci:tekton-cnb
      command: ["/bin/sh"]
      args:
        - "-c"
        - >
          cf version &&
          cf api --skip-ssl-validation $(inputs.params.API_ENDPOINT) &&
          cf auth $(inputs.params.CF_USER) $(inputs.params.CF_PASS) &&
          cf create-org $(inputs.params.CF_ORG) &&
          cf target -o $(inputs.params.CF_ORG) &&
          cf create-space $(inputs.params.CF_SPACE) &&
          cf target -o $(inputs.params.CF_ORG) -s $(inputs.params.CF_SPACE) &&
          cf enable-feature-flag diego_docker &&
          cf push test-app --docker-image  $(inputs.params.APP_IMAGE)
